# Based on https://github.com/ros-tooling/action-ros-ci

name: ROS Noetic CI

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
  push:
    branches:
      - main
jobs:
  noetic_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: noetic
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: parallel_curves
        target-ros1-distro: noetic
        import-token: ${{ secrets.GITHUB_TOKEN }}