# Based on https://github.com/ros-tooling/action-ros-ci

name: ROS Humble CI

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
  push:
    branches:
      - main
jobs:
  humble_build:
    runs-on: ubuntu-22.04
    steps:
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: parallel_curves
        target-ros2-distro: humble
        import-token: ${{ secrets.GITHUB_TOKEN }}